# Generated by Django 4.1.4 on 2023-02-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ticket',
        ),
    ]
