# Generated by Django 4.1.4 on 2023-03-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_ticketsinorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Талон для добавления к продажам', 'verbose_name_plural': 'Варианты талонов на продажу'},
        ),
    ]
